format = """
[](#3d133a)\
$os\
$username\
[](bg:#910048 fg:#3d133a)\
$directory\
[](fg:#910048 bg:#F17500)\
$git_branch\
$git_status\
[](fg:#F17500 bg:#01534f)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#01534f bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#3d133a"
style_root = "bg:#3d133a"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#3d133a"
disabled = true # Disabled by default

[directory]
style = "bg:#910048"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#01534f"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#01534f"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#015d6d"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#01534f"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#01534f"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#1a011a bg:#F17500"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#1a011a bg:#F17500"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#01534f"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#01534f"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#01534f"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#01534f"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#01534f"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#01534f"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#01534f"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#01534f"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#01534f"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'

